### ISSUE TITLE
Entity's list has the same objects multiple times

### ISSUE THREAD

**Issue by MrGazdag** [MorphiaOrg/morphia#1876] opened 2022-05-13 17:48 UTC
**Describe the bug**
I have a class marked with `@Entity`, and it has a list, that has 3 other elements, containing different data.
Example data structure:
```json
{
  "_id": "trio",
  "_t": "SaveData",
  "position": [0.2, 1.0, 2.2],
  "elements": [
    {
      "_t": "ChildData",
      "position": [4.0, -1.0, 2.2]
    },
    {
      "_t": "ChildData",
      "position": [2.0, -1.0, 4.0]
    },
    {
      "_t": "ChildData",
      "position": [-3.5, 0.0, 3.5]
    }
  ]
}
```

Java entity code:
```java
@Entity("saved_stuff")
public class SaveData {
    @Id
    public final String saveName;
    public final double[] position;
    public final List<ChildData> elements;

    public SaveData(String saveName, double[] position, List<ChildData> elements) {
        this.saveName = saveName;
        this.position = position;
        this.elements = elements;
    }
    @Entity
    public static class ChildData {
        public final double[] child_position;
        public final List<ChildData> child_elements;

        public ChildData(double[] child_position, List<ChildData> child_elements) {
            this.child_position = child_position;
            this.child_elements = child_elements;
        }
    }
}
```

After using `datastore.save(saveData)`, the object appears in the MongoDB database correctly (using Studio3T I have checked, the data contains the corrent values).
After querying the object, the `elements` list contains the same `ChildData` object 3 times, instead of 3 separate objects containing different values. This is incorrect.

**To Reproduce**
I do the following to query the object:
```java
Datastore datastore = ...;
SaveData data = datastore.find(SaveData.class).filter(Filters.eq("_id", "trio")).first();
```

Using a debugger, i can determine that in the stored data, the `elements` list contains the same object 3 times.
![image](https://user-images.githubusercontent.com/44264503/168338990-7d79b97b-f4d5-46a3-89fa-2ae13944f1fb.png)

**Expected behavior**
I expected the `elements` list to contain the 3 elements that i have saved previously.

**Please complete the following information:**
 - Server Version: 5.0.8
 - Driver Version: 4.2.2
 - Morphia Version: 2.2.6

**Comment by evanchooly** [comment] 2022-05-15 03:05
I'm not seeing this locally.  I wrapped your code up in a unit test and it passed just fine.  I inspected the objects in a debugger and it all checks out.

**Comment by MrGazdag** [comment] 2022-05-15 10:48
I have tested again, this still occurs with my setup.
Perhaps this is an issue with the configuration?

The way I get the `Datastore` object is the following:
```java
MongoClient client = MongoClients.create(MongoClientSettings.builder()
                .applyToConnectionPoolSettings(builder -> {
                    builder.minSize(5);
                    builder.applyConnectionString(new ConnectionString(Config.getMongoUri()));
                    builder.maxSize(20);
                    builder.build();
                })
                .applyConnectionString(new ConnectionString(Config.getMongoUri()))
                .build());

datastore = Morphia.createDatastore(client, Config.getMongoDatabase());
```

The `mongoUri` variable is the following:
`mongodb://localhost:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000`

I'm going to ask someone to build the project and see if it breaks for them as well. If it doesn't, then it is an issue on my end somehow, and i'll close this issue.

**Comment by MrGazdag** [comment] 2022-05-17 17:00
I had this code tested, and it appears the bug is present on other machines too, so this is not necessarily an issue related to my computer.

**Comment by evanchooly** [comment] 2022-05-17 18:26
If you could put together a [reproducer](/morphiaorg/reproducer) I'd be happy to take a look and see.

**Comment by MrGazdag** [comment] 2022-05-17 20:46
I created one [here](https://github.com/MrGazdag/entity-clone-test), it has a failing test with this problem.

**Comment by MrGazdag** [comment] 2022-05-18 16:27
I tested the reproducer with the commit f69a53aa and the test seems to pass, so this could already be fixed with 2.2.7

**Comment by WeeHorse** [comment] 2022-05-18 20:41
I can echo that we have the same breaking issue on all computers in a team of 20. We are now rolling back to 1.5.3 or 1.6.1 which is a pity, but this is a critical breaking issue that we cannot fix.

**Comment by evanchooly** [comment] 2022-05-18 21:40
You're saying 1.6.1 has this issue?  That's surprising given that it's a couple of years old at this point and no one's run in to that.  But perhaps when I figure out what's giving @MrGazdag such headaches we'll know more about 1.6.1 as well.

**Comment by MrGazdag** [comment] 2022-05-18 21:46
Again, on the latest commits on both the `master` branch and the `2.2.X` branch, the test passes and it completes successfully. (used Jitpack to build the latest commits there, and used that as the dependency)

**Comment by evanchooly** [comment] 2022-05-18 22:14
@MrGazdag I've confirmed the issue on 2.2.6 and that the fix is in 2.2.7.  My last comment was for @WeeHorse and not on your issue specifically.  I've been waiting feedback on one particular issue to confirm a fix there but I'll just push 2.2.7 to get you the fixes you need and address the other with a later release if necessary.

**Comment by evanchooly** [comment] 2022-05-18 22:15
closing as fixed

**Closed by evanchooly** 2022-05-18 22:15 UTC
Labels: bug, Waiting for Response

**Comment by WeeHorse** [comment] 2022-05-18 23:02
Hi! No, the issue is not in 1.6.1. Thanks for fixing this, will test tomorrow

**Comment by evanchooly** [comment] 2022-05-18 23:10
I just pushed 2.2.7.  It should be on central as soon as the sync finishes.  Give it an hour or two and you should be set.
