### ISSUE TITLE
 ReferenceException while calling method on referenced entity that has gone despite ignoreMissing

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#1847] opened 2022-03-11 06:35 UTC
**Describe the bug**
Let `entity` be an arbitrary entity stored in DB whose class declares a getter method named `getReferencedEntity()` for some field that is annotated with `@Reference(lazy = true, ignoreMissing = true)`.

In case the entity referenced by a field that is annotated with `@Reference(lazy = true, ignoreMissing = true)` does not exist in DB anymore, invocation of any public instance method on the proxy instance returned by Morphia throws a `ReferenceException` in Morphia v2.

This is a significant change to Morphia v1 which simply returned `null` for any public instance method on the proxy instance in case the referenced entity does not exist in DB (anymore) and the reference is annotated with `@Reference(lazy = true, ignoreMissing = true)`.

**To Reproduce**
Run the following unit test:
```java
package dev.morphia.test.mapping.lazy;

import static dev.morphia.query.experimental.filters.Filters.eq;

import org.testng.Assert;
import org.testng.annotations.Test;

import dev.morphia.Datastore;
import dev.morphia.annotations.Reference;
import dev.morphia.test.mapping.ProxyTestBase;
import dev.morphia.test.models.TestEntity;

@Test(groups = "references")
public class TestLazyIgnoreMissing extends ProxyTestBase
{
    public void testReferentIsGone() 
    {
        checkForProxyTypes();

        RootEntity root = new RootEntity();
        root.setBar("foo");
        final ReferencedEntity reference = new ReferencedEntity();
        reference.setFoo("bar");

        root.setR(reference);
        
        final Datastore datastore = getDs();
        datastore.save(reference);
        datastore.save(root);
        
        root = datastore.find(RootEntity.class)
                        .filter(eq("_id", root.getId()))
                        .first();

        final ReferencedEntity p = root.r;

        assertIsProxy(p);
        assertNotFetched(p);
        p.getFoo();
        assertFetched(p);
        
        // delete the referenced entity
        datastore.delete(reference);
        // refresh root entity
        root = datastore.find(RootEntity.class)
            .filter(eq("_id", root.getId()))
            .first();

        Assert.assertNotNull(root.r);
        Assert.assertNotNull(root.getR());
        Assert.assertNull(root.r.getFoo());
    }
    
    
    public static class RootEntity extends TestEntity {
        @Reference(idOnly = true, lazy = true, ignoreMissing = true)
        private ReferencedEntity r;
     
        private String bar;

        public String getBar()
        {
            return bar;
        }

        public void setBar(String bar)
        {
            this.bar = bar;
        }

        public ReferencedEntity getR() {
            return r;
        }

        public void setR(ReferencedEntity r) {
            this.r = r;
        }

    }

    public static class ReferencedEntity extends TestEntity {
        private String foo;


        public String getFoo() {
            return foo;
        }

        public void setFoo(String string) {
            foo = string;
        }

    }
}

```

**Expected behavior**
Proxy object returned by Morphia honors `ignoreMissing` flag as was done in Morphia v1 and returns `null` as result for any public instance method invocation.

** Please complete the following information: **
 - Server Version: 5.0
 - Driver Version: 4.4.1
 - Morphia Version: 2.0.5

**Comment by h-arlt** [comment] 2022-03-11 07:05
After some debugging I've ffound out, that the behavior in Morphia v1 originates from  `com.thoughtworks.proxy.toys.delegate.DelegatingInvoker#invoke(Object, Method, Object[])` lines 106-110.

Morphia v2 does not use this library anymore. To restore the old behavior (if desired), Morphia should mimic this aspect of DelegatingInvoker; e.g. add the following two lines before throwing the `ReferenceException` in line 60 of class `dev.morphia.mapping.codec.references.ReferenceProxy`:
```java
  if (reference.ignoreMissing())
      return target;
```

**Comment by evanchooly** [comment] 2022-03-25 04:27
This looks like a duplicate of #1811.  Feel free to reopen if that's not the case.  You can test out 2.2.7-SNAPSHOT to make sure.

**Closed by evanchooly** 2022-03-25 04:27 UTC
Labels: bug

**Comment by h-arlt** [comment] 2022-03-28 07:07
Unfortunately, it's not a duplicate of #1811. This issue is about **loading** entities that have at least one lazy reference to another entity which itself has vanished from DB (#1811 is about **saving** such an entity).

**Comment by h-arlt** [comment] 2022-03-28 08:04
Re-opened as #1860
