### ISSUE TITLE
Can't find a codec for class dev.morphia.mapping.codec.writer.NameState (v 2.2.5)

### ISSUE THREAD

**Issue by iAmcR** [MorphiaOrg/morphia#1853] opened 2022-03-15 23:10 UTC
Hi, 
It seems there are some codec (or codec configuration) changes between v2.1.4 and v2.2.5. 

Any ideas as to why in v2.2.5 I got the below stack exception while trying to save? 

Thank you. 

```
Caused by: org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class dev.morphia.mapping.codec.writer.NameState.
	at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:64)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:52)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:202)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:200)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:225)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:198)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:159)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:46)
	at dev.morphia.mapping.codec.pojo.LifecycleEncoder.encode(LifecycleEncoder.java:39)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.encode(MorphiaCodec.java:126)
	at dev.morphia.mapping.codec.CollectionCodec.encode(CollectionCodec.java:41)
	at dev.morphia.mapping.codec.CollectionCodec.encode(CollectionCodec.java:21)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.writeValue(EntityEncoder.java:103)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeValue(EntityEncoder.java:93)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.lambda$encode$0(EntityEncoder.java:46)
	at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.document(ExpressionHelper.java:36)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encode(EntityEncoder.java:33)
	at dev.morphia.mapping.codec.pojo.LifecycleEncoder.encode(LifecycleEncoder.java:35)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.encode(MorphiaCodec.java:126)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:221)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:162)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:268)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:490)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:253)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:431)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:251)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:76)
	at com.mongodb.internal.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:194)
	at com.mongodb.internal.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:185)
	at com.mongodb.internal.operation.OperationHelper.withReleasableConnection(OperationHelper.java:621)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:185)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:76)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:187)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1009)
	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:567)
	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:550)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:510)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:395)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:389)
```

**Comment by evanchooly** [comment] 2022-03-16 03:45
Well, i know the "what" of that but not the "why."  If you could put together a [reproducer](/morphiaorg/reproducer) I'd be happy to take a look and see.

**Comment by adevvv** [comment] 2022-04-25 10:32
Hello, this is a BLOCKING bug for me in Version Morphia 2.2.6. I cannot even execute one morphia query without this bug being thrown. 
I needed to update our production this week, because the database layer is updated by MongoDB, and our old software stack is not compatible any more. The last thing that's missing is the Server with the update in Morphia. But this bug is Blocking everything,. I waited to hope that this bug is fixed in Morphia by now. Any change we can have the fix with Morphia 2.2.7 and this is usable this week even?

**Comment by adevvv** [comment] 2022-04-25 10:33
Example: 
Event-Query findByContentIdOrBelongsToContentId MorphiaQuery[clazz=Event, query=Document{{customerId=5346d4c7e4b0b025e420f81c, $and=[Document{{$or=[Document{{contentId=5347c947e4b09c3c46c82a6f}}, Document{{belongsToContentId=5347c947e4b09c3c46c82a6f}}]}}, Document{{$or=[Document{{$or=[Document{{disabled=Document{{$exists=false}}}}, Document{{disabled=false}}]}}, Document{{$and=[Document{{disabled=true}}, Document{{createdByUserId=5ca265df72a6220ffd6dc6e6}}]}}, Document{{$and=[Document{{disabled=true}}, Document{{$or=[Document{{contentId=5347c947e4b09c3c46c82a6f}}]}}, Document{{belongsToContentId=5347c947e4b09c3c46c82a6f}}]}}]}}, Document{{$or=[ { start: { $gte: 2022-04-24T22:00 } }, { $and: [ { start: { $lte: 2022-04-24T22:00 } }, { end: { $gte: 2022-04-24T22:00 } } ] } ]}}], $or=[Document{{start=Document{{$gte=2022-04-24T22:00}}}}, Document{{$and=[Document{{start=Document{{$lte=2022-04-24T22:00}}}}, Document{{end=Document{{$gte=2022-04-24T22:00}}}}]}}], start=Document{{$lte=2023-04-25T10:28:32.751}}}}] find options: FindOptions[allowDiskUse=null, batchSize=0, limit=10, maxTimeMS=0, maxAwaitTimeMS=0, skip=0, sort=Document{{start=1}}, cursorType=null, noCursorTimeout=false, oplogReplay=false, partial=false, collation=null, comment='null', hint=null, max=null, min=null, returnKey=false, showRecordId=false, readPreference=null, queryLogId='null', projection=null]
22-04-25 10:28:32.779| ERROR BasicController.errorOcurred:289 - Can't find a codec for class dev.morphia.mapping.codec.writer.NameState.
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class dev.morphia.mapping.codec.writer.NameState.
	at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:64)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:52)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:202)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:200)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:225)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:198)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:159)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:46)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.BsonDocumentCodec.writeValue(BsonDocumentCodec.java:139)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:118)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.RequestMessage.addDocument(RequestMessage.java:238)
	at com.mongodb.internal.connection.RequestMessage.addDocument(RequestMessage.java:188)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:155)

**Comment by evanchooly** [comment] 2022-04-25 15:40
Can you provide a reproducer for it?  At least share your entity?

**Comment by adevvv** [comment] 2022-04-25 16:08
Can I send you the entity privately via Email or so? Don't wanna share it here.

**Comment by adevvv** [comment] 2022-04-26 10:10
That's the fields of Event object, hope this helps for finding the encoding problem with this class?

```
	@JsonIgnore
	protected ObjectId c;
	protected ObjectId c1;

	//@JsonIgnore
	@Indexed(IndexDirection.GEO2DSPHERE)
	public Point location;


	String t;
	String d;
	
	String d2;
	
	@JsonIgnore
	String d3;
	
	@JsonIgnore
	String d4;
	
	Double r;
	Integer rc;
	Long v;
	Date dc;
	Date lu;
	
	Date start;
	Date end;
	String tz;
	String o;
	String od;
	
	String fu;
	String wu;
	Integer ca;
	String tsu;
	
	String c;
	Integer pic;
	
	ObjectId cid;
	
	
	Integer cwt;

	
	Media img;
	
	
	Media mi;
	
	List<Comment> cmts;
	
	Long cmtsc;
	
	
	List<ObjectId> tgs;
	
	
	@Transient
	List<Tag> tgsobjcts;
	

	Contact contact;
	Address address;
	
	@Transient
	@JsonIgnore
	public boolean bool1 = true;
	
	@Transient
	Content ctobjct;

	
	List<Link> links;
	
	Integer va;
	Integer vi;
	Integer vw;
	
	Integer p;
	

	@JsonIgnore
	String ext;
	
	Integer exts;

	
	List<Media> medias;
	
	@Transient
	List<MediaFile> as;
	
	@Transient
	List<MediaFile> vs;
	
	@Transient
	Boolean bool2;
	
	
	Boolean atenbld;
	
	ObjectId btcId;
	
	

	@JsonIgnore
	Boolean sagl;
	
	
	@JsonIgnore
	Boolean sall;


	Integer status;
	
	Boolean disabled;
	
	String visibility;
```

**Comment by evanchooly** [comment] 2022-04-26 14:58
Are you not doing anything with lifecycles?  @PostLoad or something?

**Comment by adevvv** [comment] 2022-04-26 17:08
No, nothing fancy really. And the BO is annotated with @Entity(value="event", useDiscriminator = false). Some fields with @Transient some with @JsonIgnore . Mainly only setter + getter. The only difference to an other BO that works are the Date fields?

**Comment by evanchooly** [comment] 2022-04-26 19:53
if you could dm me on twitter with a link i can take a closer look.  You shouldn't be getting to that code without a lifecycle event so something is up.

**Comment by adevvv** [comment] 2022-04-27 10:55
Sorry, can't publish the code online under a link, and we do not do anything with lifecycles, I truly think.

**Comment by adevvv** [comment] 2022-04-28 16:32
Had this in the pom.xml still too, and outcommented it b/c maybe the proxything was causing this problem, but unfortunatly still the same error. Is this to remove for Morphia 2.2.6 or should it be kept?
I am now try/catching the morphia error in the code, and might need to go live without Events available in this release :/

`	    `

**Comment by adevvv** [comment] 2022-05-03 08:48
Update: we now went live with the error, causing our product not to be able to show Events. Hopefully we can find a solution to this BLOCKER soon. Thanks!

**Comment by adevvv** [comment] 2022-05-03 14:43
I understand that you cannot fix this now, because you cannot reproduce it. Unfortunately, I tried to provide you with the information that I can, but I cannot give you access to our closed source. Hopefully other Morphia users, can help here. Until then, we will have to accept the bug, I guess.

**Comment by evanchooly** [comment] 2022-05-03 14:55
Can you share the query itself?  Redacting/renaming fields to protect the innocent of course.  Looking at that horrendous `toString()` above, I have an idea or two.

**Comment by adevvv** [comment] 2022-05-03 15:15
The query is generated over many different methods and if/else in a big DAO, so I unfortunately cannot share this, does the generated debug message of the effective query not help?

**Comment by evanchooly** [comment] 2022-05-03 21:39
It kinda helps.  I can try to reverse engineer the query.  In the end, it might prove enough so I'll give it a shot.  I'm traveling for a conference but I'll try my best to give this some focused time over the next few days.

**Comment by evanchooly** [comment] 2022-05-06 13:26
I played around with reverse engineering the query but there's nothing about the structure of the query that would indicate how you're getting in to that part of the code.  My only theory at this point is that perhaps `Comment` has some lifecycle handlers attached to it.

**Comment by cwweng** [comment] 2022-05-12 04:18
I encounter same exception few days ago. Downgrade to v 2.2.3 seems to fix the problem.

**Comment by cwweng** [comment] 2022-05-13 03:00
Here is a simple project to recreate the problem.

MongoDB : 4.2.19 on MongoDB Atlas

On first run, all posts are inserted. On second run, all posts should be updated, but exception occurs
[morphia-test.tar.gz](https://github.com/MorphiaOrg/morphia/files/8683807/morphia-test.tar.gz)
.

**Comment by evanchooly** [comment] 2022-05-13 04:32
thank you.  i'll tackle this this weekend.

**Comment by evanchooly** [comment] 2022-05-14 02:05
ok.  it looks like i have it fixed.  at least for @cwweng's case.  @adevvv, can you try the latest 2.2.7-SNAPSHOT and see if it also fixes yours?

**Comment by evanchooly** [comment] 2022-05-18 22:16
closing this as fixed.  if you see any further issues, please file a new bug.

**Closed by evanchooly** 2022-05-18 22:16 UTC
Labels: bug

**Comment by adevvv** [comment] 2022-06-08 15:01
Hello @evanchooly, sorry I just could test it now, yes we can show Events again with morphia 2.2.7, seems to be working good! Thanks!!
