### ISSUE TITLE
beta version of org.slf4j (1.8.0-beta2) is used in non-beta public release

### ISSUE THREAD

**Issue by xtracoder** [MorphiaOrg/morphia#1382] opened 2019-09-18 19:21 UTC
Not sure ... to my mind it is not good idea to include 'beta' dependencies into 'non-beta' releases in public repository.

See Compile Dependencies here
https://mvnrepository.com/artifact/dev.morphia.morphia/core/1.5.3

Does Morphia really use some features from slf4j v1.8?
Will Morphia fail when there is only latest slf4j v1.7.xxx available in classpath?

**Comment by evanchooly** [comment] 2019-09-26 02:57
duplicate of #1365

**Closed by evanchooly** 2019-09-26 02:57 UTC
Labels: duplicate
