### ISSUE TITLE
RegexFilter `getValue` returns null instead of value

### ISSUE THREAD

**Issue by lindsaycooper** [MorphiaOrg/morphia#2249] opened 2023-02-10 05:58 UTC
**Describe the bug**
RegexFilter `getValue` returns null instead of value. This prevents the ability to validate regular expression filters in unit tests.

**To Reproduce**
Example unit test:
```
RegexFilter nameFilter = Filters.regex("name").pattern("test");
Assertions.assertEquals("name",  nameFilter.getField());
Assertions.assertEquals("$regex",  nameFilter.getName());
Assertions.assertEquals("test",  nameFilter.getValue());

Assertions.assertEquals("name $regex test",  nameFilter.toString());
```

Failures:
`Assertions.assertEquals("test",  nameFilter.getValue());`
  - Expected: `test`
  - Actual: `null`

`Assertions.assertEquals("name $regex test",  nameFilter.toString());`
  - Expected: `name $regex test`
  - Actual: `name $regex null`

**Expected behavior**
1. The `getValue` method returns the `regex` value from the filter
2. The `toString` method includes the `regex` value from the filter

**Please complete the following information:**
 - Driver Version: 4.7.2
 - Morphia Version: 2.3.0

**Comment by evanchooly** [comment] 2023-03-02 03:03
Those methods aren't really intended for users to be futzing about with as the deal with internal state.  So this isn't a bug, per se, because `RegexFilter` is doing some different things internally that shouldn't matter outside of that class.  However, it *is* ... a slightly weird way of going about it so I can clean that API up a bit in 2.4.0, at least.

So I'm going to close this as "not a bug" and file a new one to reflect that API change.

**Closed by evanchooly** 2023-03-02 03:03 UTC
Labels: invalid
