### ISSUE TITLE
Generics mapping throws NPE

### ISSUE THREAD

**Issue by talgendler** [MorphiaOrg/morphia#553] opened 2013-11-16 05:36 UTC
This example throws NPE

```
@Test
public void testListGenerics() {
    @Entity
    class BaseOne<T> {
        @Id
        ObjectId _id;
        T value;
        void setValue(T value) {
            this.value = value;
        }
    }

    class ListBase<ITEM> extends BaseOne<List<ITEM>> { }

    class ConcreteOne extends ListBase<String> {}

    ConcreteOne concreteOne = new ConcreteOne();
    List<String> strings = Arrays.asList("Hello, ", "world");
    concreteOne.setValue(strings);
    morphia.toDBObject(concreteOne);
}
```

ava.lang.NullPointerException at com.google.code.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:306) at com.google.code.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:302) at com.google.code.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:324) at com.google.code.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:302) at com.google.code.morphia.utils.ReflectionUtils.getParameterizedType(ReflectionUtils.java:281) at com.google.code.morphia.mapping.MappedField.discoverMultivalued(MappedField.java:136) at com.google.code.morphia.mapping.MappedField.discover(MappedField.java:96) at com.google.code.morphia.mapping.MappedField.(MappedField.java:76) at com.google.code.morphia.mapping.MappedClass.discover(MappedClass.java:197) at com.google.code.morphia.mapping.MappedClass.(MappedClass.java:119) at com.google.code.morphia.mapping.Mapper.getMappedClass(Mapper.java:225) at com.google.code.morphia.DatastoreImpl.getWriteConcern(DatastoreImpl.java:1346) at com.google.code.morphia.DatastoreImpl.save(DatastoreImpl.java:934)

Morphia version : 0.104
Java version : 1.6.0_45

**Comment by evanchooly** [comment] 2015-05-20 15:36
probably a dupe of #552

**Comment by evanchooly** [comment] 2016-06-06 19:15
Confirmed to work with the 2.0 mapping code

**Comment by markmgordon** [comment] 2017-09-26 17:01
I am also experiencing this bug.

I ran the test in the description on the 2.x-dev branch and it still fails.  Perhaps it worked on Jun 6, 2016, but it doesn't seem to be working now.

```
Caused by: java.lang.NullPointerException
	at org.mongodb.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:289)
	at org.mongodb.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:278)
	at org.mongodb.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:313)
	at org.mongodb.morphia.utils.ReflectionUtils.getParameterizedClass(ReflectionUtils.java:278)
	at org.mongodb.morphia.utils.ReflectionUtils.getParameterizedType(ReflectionUtils.java:265)
	at org.mongodb.morphia.mapping.MappedField.discoverMultivalued(MappedField.java:722)
	at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:490)
	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:111)
	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:583)
	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:144)
	at org.mongodb.morphia.mapping.Mapper.getMappedClass(Mapper.java:484)
	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:541)
	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:144)
	at org.mongodb.morphia.mapping.Mapper.getMappedClass(Mapper.java:484)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:969)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:581)
	at org.mongodb.morphia.Morphia.toDBObject(Morphia.java:250)
```

I'll post tests relevant to my situation in a follow up comment.

**Comment by evanchooly** [comment] 2019-10-31 03:46
Works with 2.0's mapping code

**Closed by evanchooly** 2019-10-31 03:46 UTC
Labels: bug
