### ISSUE TITLE
Support for async

### ISSUE THREAD

**Issue by Ve6om** [MorphiaOrg/morphia#2320] opened 2023-03-28 00:53 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add support for async!

**Describe alternatives you've considered**
N/A

**Additional context**
In particularly It would be great to be able to use Morphia async, rather that be supporting mongo async java driver, or another way.

**Comment by evanchooly** [comment] 2023-03-28 02:04
duplicate of #829 and #1340

**Closed by evanchooly** 2023-03-28 02:04 UTC
Labels: duplicate
