### ISSUE TITLE
NullPointerException when using update

### ISSUE THREAD

**Issue by hystrix0779** [MorphiaOrg/morphia#2472] opened 2023-08-16 07:20 UTC
Hello, I am using version 2.4.0, when performing the update operation, if the update directly, the following error will be thrown
 ```
 Exception in thread "main" java.lang.NullPointerException
	at dev.morphia.mapping.codec.pojo.PropertyModel.specializeCodec(PropertyModel.java:274)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.specializePropertyCodecs(MorphiaCodec.java:197)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.<init>(MorphiaCodec.java:69)
	at dev.morphia.mapping.codec.MorphiaCodecProvider.get(MorphiaCodecProvider.java:64)
	at org.bson.internal.ProvidersCodecRegistry.lambda$get$0(ProvidersCodecRegistry.java:76)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:74)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:67)
	at org.bson.codecs.CollectionCodec.writeValue(CollectionCodec.java:106)
	at org.bson.codecs.AbstractCollectionCodec.encode(AbstractCollectionCodec.java:111)
	at org.bson.codecs.AbstractCollectionCodec.encode(AbstractCollectionCodec.java:42)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:206)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:164)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:44)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at dev.morphia.aggregation.codecs.ExpressionHelper.value(ExpressionHelper.java:163)
	at dev.morphia.query.OperationTarget.lambda$encode$0(OperationTarget.java:72)
	at dev.morphia.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:81)
	at dev.morphia.query.OperationTarget.encode(OperationTarget.java:72)
	at dev.morphia.query.Operations.toDocument(Operations.java:74)
	at dev.morphia.query.UpdateBase.toDocument(UpdateBase.java:82)
	at dev.morphia.query.Update.execute(Update.java:50)
	at dev.morphia.query.Update.execute(Update.java:40)
	at zhongchuanyun.likes.UpdateLikes.updateUpdateLog(UpdateLikes.java:112)
	at zhongchuanyun.likes.UpdateLikes.main(UpdateLikes.java:60)
```

However, when I add query.first() before performing the update operation, I can perform the update operation as normal.Here are my entity classes

```java
package zhongchuanyun.likes.entity;

import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Id;
import dev.morphia.annotations.Property;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.bson.types.ObjectId;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Entity(value = "P4VIViT6rlmOJPEcHeEKXZlJBiURHHX4_detailextrainfo_update_log", useDiscriminator = false)
@Getter
@Setter
@ToString
public class DetailExtraInfoUpdateLog {

    /**
     * {@link DetailExtraInfo} 
     */
    @Id
    private ObjectId id;

    @Property("last_updated")
    private LocalDateTime lastUpdated;

    @Property("logs")
    private List<Map<String, Long>> logs;
 
    @Property("logs_detail")
    private List<Logs> logsDetail;


    @Getter
    @Setter
    @ToString
    @Entity(useDiscriminator = false)
    public static class Logs {

        @Property("update_time")
        private LocalDateTime updateTime;
 
        @Property("good_count")
        private Long goodsCount;

        @Property("browse_count")
        private Long browseCount;

        @Property("browse_count_new")
        private Long browseCountNew;
    }

}
```
And my operation
```java
Query<DetailExtraInfoUpdateLog> query = datastore.find(DetailExtraInfoUpdateLog.class).
                filter(Filters.eq(LikesConst.ID, updateLog.getId()));
//        query.first();
        query.update(
                UpdateOperators.set("last_updated", updateLog.getLastUpdated()),
                UpdateOperators.push("logs", updateLog.getLogs()),
                UpdateOperators.push("logs_detail", updateLog.getLogsDetail())
        ).execute();
```

**Comment by seanRoshan** [comment] 2023-08-17 18:15
@evanchooly  Update is marked as deprecated, but there is not alternative to Update.

**Comment by evanchooly** [comment] 2023-08-17 19:57
@seanRoshan that's explained here:  https://morphia.dev/morphia/2.4/preparingFor30.html#_deprecations

**Comment by Azn9** [comment] 2023-08-18 09:54
I have a similar issue, but with a slightly different stacktrace. I'll leave it below so if anyone has the same issue they will find this.
The `query.first();` "workaround" worked for this too

```
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "dev.morphia.Datastore.getCodecRegistry()" because the return value of "java.lang.ThreadLocal.get()" is null
                at dev.morphia.mapping.codec.pojo.PropertyModel.configureCodec(PropertyModel.java:374)
                at dev.morphia.mapping.codec.pojo.PropertyModel.specializeCodec(PropertyModel.java:274)
                at dev.morphia.query.filters.Filter.getValue(Filter.java:157)
                at dev.morphia.query.filters.Filters$1.encode(Filters.java:220)
                at dev.morphia.query.MorphiaQuery.lambda$getQueryDocument$0(MorphiaQuery.java:394)
                at dev.morphia.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:81)
                at dev.morphia.query.MorphiaQuery.getQueryDocument(MorphiaQuery.java:391)
                at dev.morphia.query.MorphiaQuery.toDocument(MorphiaQuery.java:266)
                at dev.morphia.query.Update.execute(Update.java:51)
                at dev.morphia.query.MorphiaQuery.update(MorphiaQuery.java:316)
...
```

**Comment by shahr** [comment] 2023-08-23 14:52
Hi all, jumping in here to add that there does seem to be a bug at least in v.2.4.1.

Steps to reproduce:
```
final Datastore morphiaDatastore = createMorphiaDatastore(databaseOptions);
 
final UserDocument updatedDocument = morphiaDatastore.find(UserDocument.class)
                .filter(Filters.eq(USER_ID_FIELD_NAME, userId))
                .modify(new ModifyOptions()
                                    .writeConcern(MAJORITY_WRITE_CONCERN)
                                    .returnDocument(ReturnDocument.AFTER),
                             UpdateOperators.set(docToUpdate));
```

This results in the following exception:
```
java.lang.NullPointerException: Cannot invoke "dev.morphia.Datastore.getCodecRegistry()" because the return value of "java.lang.ThreadLocal.get()" is null

	at dev.morphia.mapping.codec.pojo.PropertyModel.configureCodec(PropertyModel.java:374)
	at dev.morphia.mapping.codec.pojo.PropertyModel.specializeCodec(PropertyModel.java:274)
	at dev.morphia.query.OperationTarget.encode(OperationTarget.java:65)
	at dev.morphia.query.Operations.toDocument(Operations.java:74)
	at dev.morphia.query.UpdateBase.toDocument(UpdateBase.java:82)
	at dev.morphia.query.Modify.execute(Modify.java:54)
	at dev.morphia.query.MorphiaQuery.modify(MorphiaQuery.java:219)
	at testapp.MorphiaTest.name(MorphiaTest.java:47)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

@evanchooly, please  confirm that you're seeing the same - I see the ticket was added to a milestone but not sure if the issue is understood.

**Comment by evanchooly** [comment] 2023-08-23 15:08
I've been caught up in other things but seeing this stack trace, i know exactly what the issue is.  I'll prioritize this tonight.

**Comment by shahr** [comment] 2023-08-23 17:14
> I've been caught up in other things but seeing this stack trace, i know exactly what the issue is. I'll prioritize this tonight.

Thank you!

**Closed** 2023-08-23 19:18 UTC
Labels: bug

**Comment by evanchooly** [comment] 2023-08-24 04:44
2.4.2 should be up on central now.

**Comment by hystrix0779** [comment] 2023-08-24 07:44
I have updated to 2.4.2 and it works perfectly, thanks to the author
