### ISSUE TITLE
Using the unset operator on @Reference fields results in NPE

### ISSUE THREAD

**Issue by ptwohig** [MorphiaOrg/morphia#1809] opened 2022-01-26 21:48 UTC
**Describe the bug**
NPE when trying to use unset in combination with modify() when the field is annotated with ```@Reference```.

**To Reproduce**
1. Define an ```@Entity``` annotated class ```Foo``` that has an ```@Id``` annotated field.
2. Define an ```@Entity``` annotated class ```Bar``` that has an ```@Id``` annotated field and a ```@Reference``` annotated field of type ```Foo```
3. Instantiate ```Bar``` with with a null reference to ```Foo``` and save it to the database. Allow Morphia to assign ID and leave all references to ```Foo``` as ```null```.
4. Using ```Query.modify().execute(new ModifyOptions())``` attempt to unset the blank field using unset operator

**Expected behavior**
The operation succeeds, or Morphia throws a meaningful exception.

** Please complete the following information: **
 - Server Version: 3.4.5 (Yes, I know I'm way behind the tims here)
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.4

**Additional context**

Stack trace:
```
java.lang.NullPointerException
	at dev.morphia.mapping.codec.references.ReferenceCodec.collectIdValues(ReferenceCodec.java:249)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encode(ReferenceCodec.java:215)
	at dev.morphia.mapping.codec.references.ReferenceCodec.lambda$encode$0(ReferenceCodec.java:205)
	at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.document(ExpressionHelper.java:35)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encode(ReferenceCodec.java:203)
	at dev.morphia.query.OperationTarget.encode(OperationTarget.java:70)
	at dev.morphia.query.Operations.toDocument(Operations.java:84)
	at dev.morphia.query.UpdateBase.toDocument(UpdateBase.java:76)
	at dev.morphia.query.Modify.execute(Modify.java:47)
```

**Comment by ptwohig** [comment] 2022-01-26 22:00
https://github.com/ptwohig/morphia-issue-1809-reproducer

**Comment by evanchooly** [comment] 2022-03-25 02:19
This actually seems to work correctly in 2.2.6 with your reproducer.  Can you upgrade and give that a try?

**Comment by ptwohig** [comment] 2022-03-28 18:24
@evanchooly Looks like it passes for me. Now with 2.2.6 I'm getting a different issue in production code. I"ll check on my end and make a new reproducer test if it seems to be a problem with Morphia.

**Comment by evanchooly** [comment] 2022-05-15 02:17
closing this since this issue seems ok.  please open a new one if you find something else.

**Closed by evanchooly** 2022-05-15 02:17 UTC
Labels: bug, Waiting for Response
