### ISSUE TITLE
@Indexes annotations on superclasses are not honored

### ISSUE THREAD

**Issue by isaacrj** [MorphiaOrg/morphia#2005] opened 2022-08-20 17:11 UTC
**The bug**
If a class annotated wirh `@Entity` has a superclass annotated with `@Indexes`, these indexes are not  created when running `Datastore.ensureIndexes()` 

**To Reproduce**
Declare a superclass with an @Indexes annotation:
```
@Indexes({
	@Index(options = @IndexOptions(name="ix_uid", unique = true), fields = {@Field("uid")})
})
public class BaseEntity  {

	@Property("uid")
	private String uid;
        
}
```

Then declare an entity as a child of this superclass:

```
@Entity("my-entities")
public class MyEntity extends BaseEntity {
}

```
Finally, map MyEntity and run ennsureIndexes() to have the Datastore create the appropiate indexes:
```
Datastore datastore = Morphia.createDatastore(...);
datastore.getMapper().map(MyEntity.class);
datastore.ensureIndexes();
```
**Expected behavior**
The index named "ix_uid" is created on the collection named "my-entities". At least this was like this on Morphia 1.3.2

**Current behavior**
The index is not created.

** Please complete the following information: **
 - Server Version: 4.4
 - Driver Version: 4.2.3
 - Morphia Version: 2.2.7

**Comment by evanchooly** [comment] 2022-10-12 15:32
I think the problem here is that you don't have an ID field.  Morphia won't index classes without an ID because without that ID, Morphia doesn't consider them as representative of a collection.  The term I use sometimes is "top level" entity which isn't a great term but it's the best I've come up with for entities that have their own collections vs those that are stored as subdocuments in another entity's documents.  Try adding an ID field and see how that goes.

**Comment by evanchooly** [comment] 2022-10-20 19:12
I'm sitting in a keynote and had some time to play with this.  The ultimate probably is that your parent class does not have an `@Entity` annotation and without that annotation, Morphia does not scan that class to collect the index information.  Adding *that* should fix your issue.

I'm going to close this since things work as intended (if not expected) so that my 2.3.0 task list stays clean but if you have any further questions or issues, please reopen this one or file a new one and I'll take a look.

**Closed by evanchooly** 2022-10-20 19:12 UTC
Labels: bug, Waiting for Response
