### ISSUE TITLE
Property codec registration doesnt work woth ServiceLoader

### ISSUE THREAD

**Issue by daniel-exceed** [MorphiaOrg/morphia#2196] opened 2023-01-08 06:02 UTC
I  defined a codec provider that extends PropertyCodecProvider and define in manifest and module info the service i'm implementing so that MorphiaCodecProvider will load it using the ServiceLoader mechanism of java, but id didnt work.

**To Reproduce**
https://github.com/daniel-exceed/property-codec-service-loader

**Expected behavior**
any codec provider defined properly using the serviceloader mechanism will be loaded

 - Server Version: 6
 - Driver Version:4.7.2
 - Morphia Version:2.3.0

I created a pull request to fix this issue: https://github.com/MorphiaOrg/morphia/pull/2190 and map the property codec providers through mapper options like the regular codec providers are mapped

**Comment by evanchooly** [comment] 2023-06-04 02:59
So I've been playing with your PR a bit the last couple of days and have run in to a few issues.  The most pressing is that it breaks the kotlin module which uses SPI for a couple of things.  I've put together a reproducer that uses modules and I can definitely seen things break with a `module-info.java` where they work without out.  However if I add the following line to my module def it seems to pick up the new codec just fine:

```java
    provides dev.morphia.mapping.codec.MorphiaPropertyCodecProvider with com.foo.MyCodecProvider;
```
Is there a problem with simply updating your module def appropriately?

**Comment by evanchooly** [comment] 2023-06-04 03:25
In 3.0, I'm thinking this will all be done via annotations at build time so there will be discovery at runtime either way. So the less I do now with this, the less there will be to unwind in the next version.

**Comment by evanchooly** [comment] 2023-06-10 05:17
Closing as there seems to be no issue here.  I have updated the docs for the upcoming version to address this topic:  https://morphia.dev/morphia/2.4/configuration.html#_some_notes_on_serviceloader

**Closed by evanchooly** 2023-06-10 05:17 UTC
Labels: bug
