### ISSUE TITLE
Morphia OSGi ClassLoader problem (Apache Virgo)

### ISSUE THREAD

**Issue by marcottedan** [MorphiaOrg/morphia#460] opened 2013-06-25 17:53 UTC
We've been working a bit with Eclipse Virgo, an OSGi runtime container at my company.

After a few days of work, we found that the way Morphia refer to the class loader is probably wrong. The DefaultCreator class uses : 

c = Class.forName( className , true , Thread.currentThread().getContextClassLoader()

instead of : 

c = Class.forName( className)

In an OSGi runtime, the currentThread refers to the OSGi container (in Virgo, the Gemini (spring) thread used to instantiate objects). The runtime definition of the class is unknown in this class loader. If we use a "Class.forName", the thread used to instantiate the object will be the correct one (the one from the Bundle thread).

To fix it, we temporarly put a Try/Catch in the catch and relaunch another Try/Catch with a simple Class.forName("...) and it works well, thought not very elegant.

**Comment by evanchooly** [comment] 2019-11-25 03:16
duplicate of #405

**Closed by evanchooly** 2019-11-25 03:16 UTC
Labels: enhancement
